name: 'Auto Process Issues'

on:
  issue_comment:
    types: [created]

permissions:
  issues: write

jobs:
  process-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Parse comment
        id: parse
        uses: actions/github-script@v6
        with:
          script: |
            const comment = context.payload.comment.body;
            let data;
            try {
              data = JSON.parse(comment);
            } catch (err) {
              core.setFailed("JSON 파싱 실패: " + err.message);
              return;
            }
            core.setOutput("priority", data.priority || "undefined");
            core.setOutput("type", data.type || "undefined");
            core.setOutput("summary", data.Summary || "");
      - name: Handle high priority
        if: steps.parse.outputs.priority == 'high'
        uses: actions/github-script@v6
        with:
          script: |
            const issue = context.payload.issue;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              body: '!!이슈 우선순위가 **HIGH** 입니다. 즉시 확인 바랍니다.'
            });
      - name: Assign based on type
        uses: actions/github-script@v6
        with:
          script: |
            const type = '${{ steps.parse.outputs.type }}';
            const mapping = { bug: 'jonghwa-yim', enhancement: 'bob', question: 'charlie' };
            const assignee = mapping[type];
            if (assignee) {
              await github.rest.issues.addAssignees({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                assignees: [assignee],
              });
            }
